# Adapted from: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
# Adapted from: https://github.com/nickmerwin/node-coveralls/blob/master/.github/workflows/test.yml

name: Run Mocha tests

on: [push, pull_request]

jobs:
  test:
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        node-version: [19, 20, 21, 22]
        os: [ubuntu-latest, windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Clean install
        run: npm ci
      - name: Run tests 
        run: npm test
      - name: Upload coverage report to coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          flag-name: ${{ matrix.os}}-node-${{ matrix.node-version}}
          path-to-lcov: ./coverage/lcov.info
          parallel: true

  finalize:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Finish Coveralls Parallel Run
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
